### ISSUE TITLE
Feature Request: Ability to Map Buttons to a Midi Controller

### ISSUE THREAD

**Issue by wepache** [SubhadeepJasu/Ensembles#78]
It would be nice if we could map the Intro, Variation, Break, Ending, and Registry Memory to our physical buttons on our midi keyboard. This would allow the full performance to take place on the hardware instead of having to use a typing keyboard or mouse clicks.

**Comment by SubhadeepJasu** [comment]
I can do this, but I'll need some help on this myself. Since I don't own a MIDI keyboard myself (I have an arranger keyboard), I will need to know the button values as sent by the keyboard. 

If you can do this in the terminal:
`G_MESSAGES_DEBUG=all com.github.subhadeepjasu.ensembles.com`
or 
`G_MESSAGES_DEBUG=all flatpak run com.github.subhadeepjasu.ensembles.com`
and connect your MIDI keyboard. If you press the buttons or keys, it will output the MIDI signals in the terminal. You can send me the output when you press the buttons I can add that in the system.

If you want we can have a dm or call for this, since I definitely want to add more controller support for the keyboard.

**Comment by wepache** [comment]
Most definitely I can help you out. I will send you the output tomorrow morning when I get on my computer.

**Comment by wepache** [comment]
[user@fedora ~]$  G_MESSAGES_DEBUG=all flatpak run com.github.subhadeepjasu.ensembles.com

(flatpak run:2740): GLib-GIO-DEBUG: 09:36:37.798: _g_io_module_get_default: Found default implementation gvfs (GDaemonVfs) for ‘gio-vfs’

(flatpak run:2740): GLib-DEBUG: 09:36:37.798: setenv()/putenv() are not thread-safe and should not be used after threads are created

(flatpak run:2740): GLib-DEBUG: 09:36:37.798: unsetenv() is not thread-safe and should not be used after threads are created

(flatpak run:2740): flatpak-DEBUG: 09:36:37.798: No installations directory in /etc/flatpak/installations.d. Skipping

(flatpak run:2740): flatpak-DEBUG: 09:36:37.798: Opening system flatpak installation at path /var/lib/flatpak

(flatpak run:2740): flatpak-DEBUG: 09:36:37.798: Opening user flatpak installation at path /home/user/.local/share/flatpak

(flatpak run:2740): flatpak-DEBUG: 09:36:37.798: Opening user flatpak installation at path /home/user/.local/share/flatpak

(flatpak run:2740): flatpak-DEBUG: 09:36:37.798: Opening system flatpak installation at path /var/lib/flatpak

error: app/com.github.subhadeepjasu.ensembles.com/x86_64/master not installed

**Comment by wepache** [comment]
Not sure if its showing that its not installed because I running it on Fedora? I am not using Elementary OS. I don't see how that would make a difference though since I am running the flatpak version. Perhaps the command should be different?

**Comment by wepache** [comment]
Let me know where you prefer to be DM'd at.

**Comment by SubhadeepJasu** [comment]
My discord is Jazz#4300.

**Comment by SubhadeepJasu** [comment]
BTW, do let me know or ping me if you contact.

**Comment by SubhadeepJasu** [comment]
@wepache Here's a build of it with multiple MIDI controller support and initial ability to map buttons to midi controllers. (Only the style control and registry memory buttons work for now). https://github.com/SubhadeepJasu/Ensembles/suites/6697964606/artifacts/254451951

**Comment by SubhadeepJasu** [comment]
Implemented
